# Generated by Django 5.1.3 on 2025-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacao',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investigacao',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
